{{- range $secretName, $secretContent := .Values.basic }}
{{ $data := dict "type" "kubernetes.io/basic-auth" "secretName" $secretName "secretContent" $secretContent "Values" $.Values "Release" $.Release . }}
{{- include "defaultTemplate" $data }}
---
{{- end -}}