{{- range $secretName, $secretContent := .Values.basic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
{{- if $.Values.labels }}
  labels:
{{ toYaml $.Values.labels | indent 4 }}
{{- end }}
{{- if $.Values.annotations }}
  annotations:
{{ toYaml $.Values.annotations | indent 4 }}
{{- end }}
stringData:
  username:  {{ $secretContent.username }}
  password: {{ $secretContent.password }}
type: kubernetes.io/basic-auth
---
{{- end -}}
