{{- range $secretName, $secretContent := .Values.opaque }}
{{ $data := dict "type" "Opaque" "secretName" $secretName "secretContent" $secretContent "Values" $.Values . }}
{{- include "defaultTemplate" $data }}
---
{{- end -}}