apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: vaultwarden
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  DOMAIN: https://{{ .Values.ingress.hostname }}
  {{- if and .Values.smtp.host .Values.smtp.from | quote }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_SECURITY: {{ .Values.smtp.security | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_AUTH_MECHANISM: {{ .Values.smtp.authMechanism | quote }}
  SMTP_FROM: {{ .Values.smtp.from | quote }}
  SMTP_DEBUG: {{ .Values.smtp.debug | quote }}
  #SMTP_ACCEPT_INVALID_HOSTNAMES: {{ .Values.smtp.acceptInvalidHostnames | quote }}
  #SMTP_ACCEPT_INVALID_CERTS: {{ .Values.smtp.acceptInvalidCerts | quote }}
  {{- end }}
  DATA_FOLDER: "/data"
  ROCKET_PORT: {{ .Values.containerPorts.http | quote }}
  ROCKET_WORKERS: {{ .Values.rocket.workers | quote }}
  SHOW_PASSWORD_HINT: {{ .Values.showPassHint | quote }}
  SIGNUPS_ALLOWED: {{ .Values.signupsAllowed | quote }}
  INVITATIONS_ALLOWED: {{ .Values.invitationsAllowed | quote }}
  SIGNUPS_DOMAINS_WHITELIST: {{ .Values.signupDomains | quote }}
  SIGNUPS_VERIFY: {{ .Values.signupsVerify | quote }}
  WEB_VAULT_ENABLED: {{ .Values.webVaultEnabled | quote }}

{{- if ne "default" .Values.database.type }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-start" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: vaultwarden
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  database.sh: |-
    #!/bin/sh

    export DATABASE_URL="{{ printf "postgresql://%s:${DATABASE_PASSWORD}@%s:%s/%s" (include "vaultwarden.databaseUser" .) (include "vaultwarden.databaseHost" .) (include "vaultwarden.databasePort" .) (include "vaultwarden.databaseName" .) }}"
{{- end }}