apiVersion: v1
kind: Service
metadata:
  name: alb-controller
  namespace: {{ include "albController.namespace" . }}
spec:
  ports:
    - name: http
      port: 8000
    - name: metrics
      port: 8001
  selector:
    app: alb-controller
  type: ClusterIP