{{- if not (eq  .Release.Namespace .Values.albController.namespace) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "albController.namespace" . }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.albController.podIdentity }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.albController.podIdentity.clientID }}
  labels:
    azure.workload.identity/use: "true"
  {{- end }}
  name: alb-controller-sa
  namespace: {{ include "albController.namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alb-controller-cluster-role
  labels:
    app: alb-controller
rules:
  - apiGroups: [""]
    resources: ["secrets", "events"]
    verbs: ["list", "get", "watch","create", "update", "delete", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["alb.networking.azure.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints", "namespaces", "services", "nodes", "pods", "configmaps"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses", "ingresses", "ingresses/status"]
    verbs: ["list", "get", "watch", "update", "patch", "create"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["update", "patch", "create"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["acn.azure.com"]
    resources: ["overlayextensionconfigs"]
    verbs: ["list", "get", "watch","create", "update", "delete", "patch"]
  - apiGroups: ["acn.azure.com"]
    resources: ["nodenetworkconfigs"]
    verbs: ["list", "get", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alb-controller-cluster-role-binding
  labels:
    app: alb-controller
subjects:
  - kind: ServiceAccount
    name: alb-controller-sa
    namespace: {{ include "albController.namespace" . }}
roleRef:
  kind: ClusterRole
  name: alb-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io