kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "flannel.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "flannel.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "flannel.name" . }}
